# Generated by Django 6.0.2 on 2026-02-18 21:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Image')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_approx', models.CharField(blank=True, max_length=100, verbose_name='Date approximative')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
            ],
            options={
                'verbose_name': 'Photographie ancienne',
                'verbose_name_plural': 'Photographies anciennes',
            },
        ),
    ]
