# Generated by Django 6.0.2 on 2026-04-07 20:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'auteur")),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la source')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien vers la source')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Storymap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='Introduction')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='storymaps/thumbnails/', verbose_name='Vignette (image de couverture)')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Storymap',
                'verbose_name_plural': 'Storymaps',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image locale')),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name="URL de l'image (ex: IIIF)")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('is_approximate', models.BooleanField(default=False, verbose_name='Date approximative')),
                ('azimuth', models.IntegerField(default=0, help_text='Direction de la prise de vue', verbose_name='Azimut (0-360°)')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.author', verbose_name='Auteur')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Photographie ancienne',
                'verbose_name_plural': 'Photographies anciennes',
            },
        ),
        migrations.CreateModel(
            name='StorymapChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du chapitre')),
                ('narrative', models.TextField(blank=True, verbose_name='Texte narratif')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude (centre carte)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude (centre carte)')),
                ('zoom', models.FloatField(default=14, verbose_name='Zoom')),
                ('baselayer', models.CharField(choices=[('darkMatter', 'Sombre (Dark Matter)'), ('voyager', 'Clair (Voyager)'), ('ortho1950', 'Ortho 1950–1965'), ('ortho1965', 'Ortho 1965–1980')], default='darkMatter', max_length=20, verbose_name='Fond de plan')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.photo', verbose_name='Photo mise en avant')),
                ('storymap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='photos.storymap', verbose_name='Storymap')),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order'],
            },
        ),
    ]
