# Generated by Django 6.0.2 on 2026-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_author_source_remove_photo_date_approx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien vers la source'),
        ),
    ]
