# Generated by Django 6.0.2 on 2026-02-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
