# Generated by Django 6.0.2 on 2026-02-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='azimuth',
            field=models.IntegerField(default=0, help_text='Direction de la prise de vue', verbose_name='Azimut (0-360°)'),
        ),
    ]
