# Generated by Django 6.0.2 on 2026-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_azimuth'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name="URL de l'image (ex: IIIF)"),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image locale'),
        ),
    ]
