# Generated by Django 6.0.2 on 2026-03-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_storymap_storymapchapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymapchapter',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude (centre carte)'),
        ),
        migrations.AlterField(
            model_name='storymapchapter',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude (centre carte)'),
        ),
    ]
