# Generated by Django 6.0.2 on 2026-03-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_storymapchapter_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymap',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='storymaps/thumbnails/', verbose_name='Vignette (image de couverture)'),
        ),
    ]
